environment: ENC[AES256_GCM,data:Q5HzpC7R,iv:gJp/K0TEdyHygPG93g9xNYAOmwiB/zd0VkDSP34hzAk=,tag:k3eop3xJxAtL6hc/Y7fVXQ==,type:str]
name: ENC[AES256_GCM,data:T/vZiWisfZI0zYszbA9Aauc=,iv:opcQpwTtc/tjtdDUFxubZp4D1biIEjVbceAyXyj23R8=,tag:M2dd6YU9gxadxbzKrvmeBA==,type:str]
port: ENC[AES256_GCM,data:Md6mQw==,iv:Z1JSGcK0KuXYQndokv/WKKRXygmYoK66dzTBioY3ol8=,tag:lTdp/IwWKlNySAbqu74eiQ==,type:int]
metrics: ENC[AES256_GCM,data:P/g1ikY=,iv:peBBCptk+O0BeIlduaid34dJix2exWU5Q+sdkmoo38k=,tag:NeGchyncm2vtwdP/5sC8Ug==,type:bool]
contracts:
    vaultManagerAddress: ENC[AES256_GCM,data:CnSdaNU3/1tyaxkJZJdf6WPwhnDorJHhafb857F4HTjCHD1BnzvHV3Z5,iv:JTT9rmTbMbPUj3XhSPLn6qFN2jmPHM3afg88ICw2XHI=,tag:O2A0uD0U6gHVDmyVLcxhEA==,type:str]
keys:
    admin: ENC[AES256_GCM,data:EaUmh30kLmBQRga/LuCHkolWXHf1hH7X2XnJ7fKDqp9/fepUoWz0IdNARE1e4Szy8zEOO6WnTPKjV0s4lP7Ecg==,iv:GU4IIK0DdadIDl13BcKMo2OgxLVi7ugLWHWhHYBl620=,tag:9oDS+8D+jqJOuwcH3W1SQw==,type:str]
infura:
    url: ENC[AES256_GCM,data:CjyqGsnvUDX0iSskmZeNgItn/+8RC9/6/LHYq9Q=,iv:GhbdL1k0tmqqMoaRn+SkP0fcHLmXa0+lqe9ka6FGdvg=,tag:xCwMV0oJ1IXrDq6NYaiuDw==,type:str]
    key: ENC[AES256_GCM,data:RkFRYwU7Q4uZNaTWIeiZczhXywEAoQF6SQi5eoVIlIM=,iv:GEG/VC4bpKRh4NpGVkHmZAevCg8pnj9BOx78YglwzFM=,tag:Iha+U90ZTpWfRsQELFheiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2019-12-01T15:36:30Z'
    mac: ENC[AES256_GCM,data:hZBhS+M8TxNoBiEFPpcACPImsK4N4dRVb4ifrJfHdtqYJROH3RZ5GHTWvWJ3lYlGoMKPVtK1M6kFe7hEpvUSpbhbUWwG5lqwh+e+h/hDU+neEYC7VBPXGyNpWUgBz4DGXt5yxNE1zN62Q0NRF8vLbd6gPK54qOSqukrVjqj0Oug=,iv:gysF/jusfc9TQd/1FREY/v+C+uzx0PeLAjLwHZFcJrA=,tag:McgIyr8gsXmm4EoXynVXHQ==,type:str]
    pgp:
    -   created_at: '2019-12-01T15:36:29Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAxcmV5QPlTskAQv/XsADf853aZtsslh8WHYapQnzVRdcAm5emJTog6IYf5I3
            yBf6yxL2xHYxVFLsdCeGHkzBDPOdTNPxWlpxIxWA14OFqvQ7rs9aMMsST05wdGfA
            7Le/VBccN0b3AfUfnP6Y77bymC4pDizrcL+i5rh69sKJTbYnLX4Arqxpy59y9FF4
            EapNDW0IR8zC0l1lpqhUsvOf76hugyoxY7FMjcE4oq9v+/rTV2OyeAE0lj7aFcIr
            3B6C2GOqYxpHbMn50HeXCKRvXQ0ptBdY+eWJAAkYGHvzzNvb79uTKE6YmwBeBDWf
            QfJUHwAEgiug/lZ6agjF75KlWXRKxMkbJctggy6HfAevDSpfBpoyO/xiqKo9BCCq
            NyW5rUa3MIeFAqTipwyItjdFyaRJqWTScImoZxn8bWzs9AjHUCFjjOelmn7Bo0pZ
            X+kzgtngPIKdMkJYt4HlfRR4ctpmQmpGVBOrO/uWd1TZSNwWZBtLO3SzjR73QcWD
            rxHHWHXnxBVHtQlsO4xN0l4B/kKte9B+aKj6vBXlm9vR/1bTvow/24uJMDk4XFvN
            w2sPdRB5V0W4aDmWAfgHufMFmBNxL8W+fvFVffRaD3Y9xNW3Yliy0HUKD7j//kD0
            fsgX1eR+p9yCD/+ZagkH
            =dv9s
            -----END PGP MESSAGE-----
        fp: 47C52A44009F2CDD681FEF9CF92E5E7AE9DCCB07
    unencrypted_suffix: _unencrypted
    version: 3.4.0