openapi: 3.0.1
info:
  title: Vault abstraction
  description: Service layer for Vault contracts
  contact:
    email: support@bam.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
tags:
- name: vault-abstraction
  description: Vault abstraction service layer
  externalDocs:
    description: Find out more
    url: http://swagger.io
paths:
  /ipfs-media-platform/health/status:
    get:
      tags:
      - ipfs-media-platform
      summary: Check the health of the service
      operationId: healthCheck
      responses:
        200:
          description: healthy response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Health'
        404:
          description: Not found
          content: {}
        401:
          description: Unauthorized
          content: {}
      security:
      - auth:
        - bam:access
  /ipfs-media-platform/manager/get-all-vaults:
    get:
      tags:
      - ipfs-media-platform
      summary: Get all vaults
      operationId: getVaults
      responses:
        200:
          description: healthy response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AllAddresses'
components:
  schemas:
    Health:
      type: object
      properties:
        message:
          type: string
          example: Healthy response from service at - 2019-10-28 01:15:49.392631014 +0000 GMT m=+72.576498242
        statusCode:
          type: number
          example: 200
    AllAddresses:
      type: object
      properties:
        addressList:
          type: string
          example: 0xA116c0dF8048741AAA9f6C46118faA92527b6221
        statusCode:
          type: number
          example: 200